services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_rpwd
      MYSQL_DATABASE: asterisk
      MYSQL_USER: asterisk
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_upwd
    secrets:
      - mysql_upwd
      - mysql_rpwd
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pbxnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 10s

  freepbx:
    image: tiredofit/freepbx:latest
    depends_on:
      - mail
      - mariadb
      - phpmyadmin
      - redis
      - tts
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: asterisk
      DB_PASS: asterisk
      DB_NAME: asterisk
      RTP_START: 10000
      RTP_FINISH: 20000
      LANGUAGE: pt_BR
      ENABLE_XMPP: true
      ENABLE_SSL: true
      ENABLE_FOP: true
    secrets:
      - mysql_upwd
    volumes:
      - freepbx_etc:/etc/asterisk
      - freepbx_lib:/var/lib/asterisk
      - freepbx_voicemail:/var/spool/asterisk/voicemail
      - freepbx_recordings:/var/spool/asterisk/recordings
      - freepbx_logs:/var/log/asterisk
      - freepbx_sounds:/var/lib/asterisk/sounds
    networks:
      - pbxnet
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "4569:4569/tcp"
      - "4569:4569/udp"
      - "8001:80"
      - "10000-20000:10000-20000/udp"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 10
        delay: 10s
    tty: true
    stdin_open: true

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: asterisk
      PMA_PASSWORD_FILE: /run/secrets/mysql_upwd
    secrets:
      - mysql_upwd
    networks:
      - pbxnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 10s

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - pbxnet
    deploy:
      restart_policy:
        condition: on-failure

  tts:
    image: ghcr.io/coqui-ai/tts:latest
    command: >
      tts-server
      --model_name tts_models/en/ljspeech/tacotron2-DDC
      --port 5002
    ports:
      - "5002:5002"
    networks:
      - pbxnet
    deploy:
      restart_policy:
        condition: on-failure


  smtp:
    image: bytemark/smtp:latest
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      RELAY_USERNAME: alice@gmail.com
      RELAY_PASSWORD: _secretpassword
    secrets:
      - smtp_userpwd
    volumes:
      - smtp_data:/var/mail
    networks:
      - pbxnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  mariadb_data:
  freepbx_etc:
  freepbx_lib:
  freepbx_voicemail:
  freepbx_recordings:
  freepbx_logs:
  freepbx_sounds:
  phpmyadmin_data:
  asterisk_tts_data:
  smtp_data:

networks:
  pbxnet:
    external: true

secrets:
  mysql_upwd:
    external: true
  mysql_rpwd:
    external: true
  smtp_userpwd:
    external: true
  # tts_key:
  #   external: true