services:
  pbx:
    image: tiredofit/freepbx:latest
    depends_on:
      - mail
      - mariadb
      - phpmyadmin
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ASTERISK_CORE_MAXLOAD: 0.9
      ASTERISK_CACHE_MEDIA_FRAMES: "yes"
      RTP_START: 10000
      RTP_FINISH: 20000
      LANGUAGE: pt_BR
      ENABLE_XMPP: "true"
      ENABLE_SSL: "true"
      ENABLE_FOP: "true"
    volumes:
      - freepbx_etc:/etc/asterisk
      - freepbx_lib:/var/lib/asterisk
      - freepbx_voicemail:/var/spool/asterisk/voicemail
      - freepbx_recordings:/var/spool/asterisk/recordings
      - freepbx_logs:/var/log/asterisk
      - freepbx_sounds:/var/lib/asterisk/sounds
      - /root/remote_code_hub.png:/var/www/html/admin/images/remote_code_hub.png:ro
      - /root/rpnv.png:/var/www/html/admin/images/rpnv.png:ro
    networks:
      - pbxnet
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5160:5160/tcp"
      - "5160:5160/udp"
      - "4569:4569/tcp"
      - "4569:4569/udp"
      - "8000:80"
      - "8443:443"
      - "8001:8001"
      - "8003:8003"
      - "8008-8009:8008-8009"
      - "10000-20000:10000-20000/udp"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    tty: true
    stdin_open: true

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pbxnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
      - mariadb
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
    networks:
      - pbxnet
    ports:
      - "8002:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  smtp:
    image: bytemark/smtp:latest
    environment:
      RELAY_HOST: ${SMPT_HOST}
      RELAY_PORT: 587
      RELAY_USERNAME: ${SMTP_USER}
      RELAY_PASSWORD: ${SMTP_PASS}
    volumes:
      - smtp_data:/var/mail
    networks:
      - pbxnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  mariadb_data:
    driver: local
  freepbx_etc:
    driver: local
  freepbx_lib:
    driver: local
  freepbx_voicemail:
    driver: local
  freepbx_recordings:
    driver: local
  freepbx_logs:
    driver: local
  freepbx_sounds:
    driver: local
  phpmyadmin_data:
    driver: local
  smtp_data:
    driver: local

networks:
  pbxnet:
    external: true
 